#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from sematic.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 3 "sematic.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "symbol.c"

int yydebug=1;
int scope,max_scope;
int errors=0;
char *tt;

mySymTab(char *type,char *sym_name,int size,int scope)
{
	symtab *s;
	s=getFromSymTab(sym_name,scope);
	if(s==0)
		s=addToSymTab(type,sym_name,size,scope);
	else
		printf("Identifier: %s is previously declared in scope: %d\n",sym_name,s->scpe);
	}

context_check(char *sym_name,int scope)
{
	symtab *s;
	s=getFromSymTab(sym_name, scope);
	if(s!=0)
	{
	}
	else
	{
		errors++;
		printf("%s is undeclared identifier!!!\n",sym_name);
		
	}
}


#line 41 "sematic.y"
typedef union{
	char *id;
	int num;
	struct decl{
		int n;
		double d;
		char *c;
		char *typ;
		}myst;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ID	258
#define	CHAR_CONSTNT	259
#define	STRNG	260
#define	Int	261
#define	IF	262
#define	ELSE	263
#define	WHILE	264
#define	FOR	265
#define	BREAK	266
#define	CASE	267
#define	CHAR	268
#define	MAIN	269
#define	DO	270
#define	CONTINUE	271
#define	DEFAULT	272
#define	SWITCH	273
#define	VOID	274
#define	INT	275
#define	Error	276
#define	RETURN	277
#define	OP_INC	278
#define	OP_DEC	279
#define	OP_BITLFT	280
#define	OP_BITRHT	281
#define	OP_LE	282
#define	OP_GE	283
#define	OP_EQ	284
#define	OP_NOT	285
#define	OP_LAND	286
#define	OP_LOR	287
#define	ASGN_RHT	288
#define	ASGN_LFT	289
#define	ASGN_ADD	290
#define	ASGN_SUB	291
#define	ASGN_MUL	292
#define	ASGN_DIV	293
#define	ASGN_MOD	294
#define	ASGN_AND	295
#define	ASGN_XOR	296
#define	ASGN_OR	297


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ID;
static const int CHAR_CONSTNT;
static const int STRNG;
static const int Int;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int BREAK;
static const int CASE;
static const int CHAR;
static const int MAIN;
static const int DO;
static const int CONTINUE;
static const int DEFAULT;
static const int SWITCH;
static const int VOID;
static const int INT;
static const int Error;
static const int RETURN;
static const int OP_INC;
static const int OP_DEC;
static const int OP_BITLFT;
static const int OP_BITRHT;
static const int OP_LE;
static const int OP_GE;
static const int OP_EQ;
static const int OP_NOT;
static const int OP_LAND;
static const int OP_LOR;
static const int ASGN_RHT;
static const int ASGN_LFT;
static const int ASGN_ADD;
static const int ASGN_SUB;
static const int ASGN_MUL;
static const int ASGN_DIV;
static const int ASGN_MOD;
static const int ASGN_AND;
static const int ASGN_XOR;
static const int ASGN_OR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ID=258
	,CHAR_CONSTNT=259
	,STRNG=260
	,Int=261
	,IF=262
	,ELSE=263
	,WHILE=264
	,FOR=265
	,BREAK=266
	,CASE=267
	,CHAR=268
	,MAIN=269
	,DO=270
	,CONTINUE=271
	,DEFAULT=272
	,SWITCH=273
	,VOID=274
	,INT=275
	,Error=276
	,RETURN=277
	,OP_INC=278
	,OP_DEC=279
	,OP_BITLFT=280
	,OP_BITRHT=281
	,OP_LE=282
	,OP_GE=283
	,OP_EQ=284
	,OP_NOT=285
	,OP_LAND=286
	,OP_LOR=287
	,ASGN_RHT=288
	,ASGN_LFT=289
	,ASGN_ADD=290
	,ASGN_SUB=291
	,ASGN_MUL=292
	,ASGN_DIV=293
	,ASGN_MOD=294
	,ASGN_AND=295
	,ASGN_XOR=296
	,ASGN_OR=297


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::ID=258;
const int YY_parse_CLASS::CHAR_CONSTNT=259;
const int YY_parse_CLASS::STRNG=260;
const int YY_parse_CLASS::Int=261;
const int YY_parse_CLASS::IF=262;
const int YY_parse_CLASS::ELSE=263;
const int YY_parse_CLASS::WHILE=264;
const int YY_parse_CLASS::FOR=265;
const int YY_parse_CLASS::BREAK=266;
const int YY_parse_CLASS::CASE=267;
const int YY_parse_CLASS::CHAR=268;
const int YY_parse_CLASS::MAIN=269;
const int YY_parse_CLASS::DO=270;
const int YY_parse_CLASS::CONTINUE=271;
const int YY_parse_CLASS::DEFAULT=272;
const int YY_parse_CLASS::SWITCH=273;
const int YY_parse_CLASS::VOID=274;
const int YY_parse_CLASS::INT=275;
const int YY_parse_CLASS::Error=276;
const int YY_parse_CLASS::RETURN=277;
const int YY_parse_CLASS::OP_INC=278;
const int YY_parse_CLASS::OP_DEC=279;
const int YY_parse_CLASS::OP_BITLFT=280;
const int YY_parse_CLASS::OP_BITRHT=281;
const int YY_parse_CLASS::OP_LE=282;
const int YY_parse_CLASS::OP_GE=283;
const int YY_parse_CLASS::OP_EQ=284;
const int YY_parse_CLASS::OP_NOT=285;
const int YY_parse_CLASS::OP_LAND=286;
const int YY_parse_CLASS::OP_LOR=287;
const int YY_parse_CLASS::ASGN_RHT=288;
const int YY_parse_CLASS::ASGN_LFT=289;
const int YY_parse_CLASS::ASGN_ADD=290;
const int YY_parse_CLASS::ASGN_SUB=291;
const int YY_parse_CLASS::ASGN_MUL=292;
const int YY_parse_CLASS::ASGN_DIV=293;
const int YY_parse_CLASS::ASGN_MOD=294;
const int YY_parse_CLASS::ASGN_AND=295;
const int YY_parse_CLASS::ASGN_XOR=296;
const int YY_parse_CLASS::ASGN_OR=297;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		192
#define	YYFLAG		-32768
#define	YYNTBASE	62

#define YYTRANSLATE(x) ((unsigned)(x) <= 297 ? yytranslate[x] : 90)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    47,     2,     2,    49,
    50,    45,    43,    52,    44,     2,    46,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    57,    51,    60,
    58,    61,    59,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    53,     2,    54,    48,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    55,     2,    56,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     6,     8,    10,    16,    22,    27,    33,
    38,    42,    44,    47,    51,    53,    56,    59,    63,    70,
    72,    74,    76,    82,    90,    96,   106,   108,   116,   122,
   132,   134,   141,   149,   151,   154,   157,   160,   164,   166,
   168,   169,   175,   179,   180,   184,   187,   188,   192,   194,
   198,   202,   206,   210,   214,   218,   220,   226,   228,   232,
   234,   238,   240,   244,   246,   250,   254,   256,   260,   264,
   268,   272,   274,   278,   282,   284,   288,   292,   296,   298,
   300,   302,   304,   309,   313,   315
};

static const short yyrhs[] = {    63,
    62,     0,     0,    65,     0,    64,     0,    70,     0,    69,
    49,    68,    50,    51,     0,    69,    49,    66,    50,    51,
     0,    69,    49,    50,    51,     0,    69,    49,    66,    50,
    77,     0,    69,    49,    50,    77,     0,    67,    52,    66,
     0,    67,     0,    71,     3,     0,    71,    52,    68,     0,
    71,     0,    71,    14,     0,    71,     3,     0,    71,     3,
    51,     0,    71,     3,    53,    79,    54,    51,     0,    13,
     0,    20,     0,    70,     0,     7,    49,    79,    50,    72,
     0,     7,    49,    79,    50,    73,     8,    72,     0,     9,
    49,    79,    50,    72,     0,    10,    49,    75,    51,    75,
    51,    75,    50,    72,     0,    74,     0,     7,    49,    79,
    50,    73,     8,    73,     0,     9,    49,    79,    50,    73,
     0,    10,    49,    75,    51,    75,    51,    75,    50,    73,
     0,    74,     0,    15,    72,     9,    49,    79,    50,     0,
    18,    49,    79,    50,    55,    76,    56,     0,    77,     0,
    79,    51,     0,    11,    51,     0,    16,    51,     0,    22,
    79,    51,     0,    51,     0,    79,     0,     0,    12,    89,
    57,    78,    76,     0,    17,    57,    78,     0,     0,    55,
    78,    56,     0,    72,    78,     0,     0,    79,    52,    80,
     0,    80,     0,    81,    58,    80,     0,    81,    35,    80,
     0,    81,    36,    80,     0,    81,    37,    80,     0,    81,
    38,    80,     0,    81,    41,    80,     0,    81,     0,    82,
    59,    81,    57,    81,     0,    82,     0,    82,    32,    83,
     0,    83,     0,    83,    31,    84,     0,    84,     0,    84,
    48,    85,     0,    85,     0,    85,    29,    86,     0,    85,
    30,    86,     0,    86,     0,    86,    60,    87,     0,    86,
    61,    87,     0,    86,    27,    87,     0,    86,    28,    87,
     0,    87,     0,    87,    43,    88,     0,    87,    44,    88,
     0,    88,     0,    88,    45,    89,     0,    88,    46,    89,
     0,    88,    47,    89,     0,    89,     0,     6,     0,     5,
     0,     4,     0,     3,    49,    79,    50,     0,     3,    49,
    50,     0,     3,     0,    49,    79,    50,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    71,    72,    75,    76,    77,    80,    81,    82,    85,    86,
    90,    91,    94,    97,    98,   101,   102,   105,   106,   109,
   110,   113,   114,   115,   116,   117,   118,   121,   122,   123,
   124,   127,   128,   129,   130,   131,   132,   133,   134,   137,
   138,   141,   142,   143,   146,   149,   150,   153,   154,   157,
   158,   159,   160,   161,   162,   163,   166,   167,   170,   171,
   174,   175,   178,   179,   182,   183,   184,   187,   188,   189,
   190,   191,   194,   195,   196,   199,   200,   201,   202,   205,
   206,   207,   208,   209,   210,   211
};

static const char * const yytname[] = {   "$","error","$illegal.","ID","CHAR_CONSTNT",
"STRNG","Int","IF","ELSE","WHILE","FOR","BREAK","CASE","CHAR","MAIN","DO","CONTINUE",
"DEFAULT","SWITCH","VOID","INT","Error","RETURN","OP_INC","OP_DEC","OP_BITLFT",
"OP_BITRHT","OP_LE","OP_GE","OP_EQ","OP_NOT","OP_LAND","OP_LOR","ASGN_RHT","ASGN_LFT",
"ASGN_ADD","ASGN_SUB","ASGN_MUL","ASGN_DIV","ASGN_MOD","ASGN_AND","ASGN_XOR",
"ASGN_OR","'+'","'-'","'*'","'/'","'%'","'^'","'('","')'","';'","','","'['",
"']'","'{'","'}'","':'","'='","'?'","'<'","'>'","Decls","Decl","Func_proto",
"Func_decl","Params","Param","Types","Func_id","Var_decl","Type","Stm","Then_stm",
"Normal_stm","Arg","Case_stms","Block","Stm_list","Expr","Op_assign","Op_if",
"Op_or","Op_and","Op_pow","Op_equate","Op_compare","Op_add","Op_mult","Value",
""
};
#endif

static const short yyr1[] = {     0,
    62,    62,    63,    63,    63,    64,    64,    64,    65,    65,
    66,    66,    67,    68,    68,    69,    69,    70,    70,    71,
    71,    72,    72,    72,    72,    72,    72,    73,    73,    73,
    73,    74,    74,    74,    74,    74,    74,    74,    74,    75,
    75,    76,    76,    76,    77,    78,    78,    79,    79,    80,
    80,    80,    80,    80,    80,    80,    81,    81,    82,    82,
    83,    83,    84,    84,    85,    85,    85,    86,    86,    86,
    86,    86,    87,    87,    87,    88,    88,    88,    88,    89,
    89,    89,    89,    89,    89,    89
};

static const short yyr2[] = {     0,
     2,     0,     1,     1,     1,     5,     5,     4,     5,     4,
     3,     1,     2,     3,     1,     2,     2,     3,     6,     1,
     1,     1,     5,     7,     5,     9,     1,     7,     5,     9,
     1,     6,     7,     1,     2,     2,     2,     3,     1,     1,
     0,     5,     3,     0,     3,     2,     0,     3,     1,     3,
     3,     3,     3,     3,     3,     1,     5,     1,     3,     1,
     3,     1,     3,     1,     3,     3,     1,     3,     3,     3,
     3,     1,     3,     3,     1,     3,     3,     3,     1,     1,
     1,     1,     4,     3,     1,     3
};

static const short yydefact[] = {     2,
    20,    21,     2,     4,     3,     0,     5,     0,     1,     0,
    17,    16,     0,     0,    12,     0,    15,    18,     0,     8,
    47,    10,     0,     0,     0,    13,     0,    85,    82,    81,
    80,     0,     0,    49,    56,    58,    60,    62,    64,    67,
    72,    75,    79,     0,     0,     0,     0,     0,     0,     0,
     0,    39,    22,     0,    47,    27,    34,     0,     0,     7,
     9,    11,     0,     6,    14,    15,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    41,    36,     0,    37,     0,     0,     0,
    46,    45,    35,    84,     0,    86,    48,    19,    51,    52,
    53,    54,    55,    50,    59,     0,    61,    63,    65,    66,
    70,    71,    68,    69,    73,    74,    76,    77,    78,     0,
     0,     0,    40,     0,     0,    38,    83,     0,     0,     0,
    41,     0,     0,    57,     0,     0,     0,    23,     0,    27,
    25,     0,     0,    44,     0,     0,    41,     0,    41,    32,
     0,     0,     0,     0,     0,     0,    24,     0,     0,    47,
    33,     0,     0,    41,     0,    47,    43,     0,    29,     0,
    26,    44,     0,    41,    42,    28,     0,     0,    30,     0,
     0,     0
};

static const short yydefgoto[] = {     9,
     3,     4,     5,    14,    15,    16,     6,    53,    54,    55,
   149,    56,   132,   163,    57,    58,    59,    34,    35,    36,
    37,    38,    39,    40,    41,    42,    43
};

static const short yypact[] = {    11,
-32768,-32768,    11,-32768,-32768,   -47,-32768,    16,-32768,     9,
    25,-32768,    30,   -24,   -13,    -5,    14,-32768,    64,-32768,
     5,-32768,    36,    11,     7,-32768,    11,    22,-32768,-32768,
-32768,    64,    50,-32768,   110,    -4,    58,    69,    68,    65,
    90,    74,-32768,    78,    81,   138,    56,     5,   137,   140,
    64,-32768,-32768,   146,     5,-32768,-32768,   134,   102,-32768,
-32768,-32768,   188,-32768,-32768,   141,    59,    60,    64,   143,
    64,    64,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    64,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    64,    64,    64,-32768,   183,-32768,    64,   106,    25,
-32768,-32768,-32768,-32768,    91,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    58,   139,    69,    68,    65,    65,
    90,    90,    90,    90,    74,    74,-32768,-32768,-32768,   100,
   114,   144,   145,   149,   125,-32768,-32768,    64,    31,     5,
    64,    64,   147,-32768,   150,   151,   152,-32768,   195,   196,
-32768,   154,   126,    40,    64,    64,    64,     5,    64,-32768,
    64,   153,   155,   129,   130,   156,-32768,   158,   157,     5,
-32768,    31,    31,    64,     5,     5,-32768,   198,-32768,   161,
-32768,    40,    31,    64,-32768,-32768,   159,    31,-32768,   213,
   215,-32768
};

static const short yypgoto[] = {   216,
-32768,-32768,-32768,   193,-32768,   191,-32768,   103,   132,   -44,
   -72,   -89,   -69,    37,    20,   -52,   -19,    98,   -77,-32768,
   148,   142,   160,   104,    77,    96,   -84
};


#define	YYLAST		240


static const short yytable[] = {    33,
   116,    10,   101,    96,   127,   128,   129,    28,    29,    30,
    31,    44,    68,    45,    46,    47,    26,     1,    11,    48,
    49,     1,    50,     1,     2,    23,    51,    77,     2,    12,
     2,    99,    22,    28,    29,    30,    31,   145,    24,   146,
   147,    47,    61,     1,    25,    48,    49,   105,    50,   150,
     2,   161,    51,    32,    78,    52,   162,    64,    13,    21,
   144,    28,    29,    30,    31,    27,    28,    29,    30,    31,
    67,   152,   130,   131,   133,    18,   169,    19,   135,    32,
    20,    52,   150,   150,    21,    21,    60,   166,    79,   168,
    21,    83,    84,   150,   148,   151,    81,    82,   150,   178,
   179,    69,     7,    70,   180,     7,    95,    32,   104,   106,
   186,    69,    32,   167,   187,   189,    80,   177,    89,    90,
    91,   133,   153,   182,    85,    86,    92,   148,   151,    93,
   181,     8,    87,    88,     8,   164,   165,   133,   167,   133,
   137,    17,    69,   181,    71,    72,    73,    74,   100,   139,
    75,    69,   103,    69,   133,    63,   136,    69,    66,   121,
   122,   123,   124,   140,   133,    69,   107,    76,   109,   110,
   111,   112,   113,   114,   143,   160,    69,    69,   172,   173,
    69,    69,   125,   126,   119,   120,    94,    97,    98,   102,
    26,   134,    27,   108,   141,   138,    69,   142,   155,   156,
   157,   154,   158,   -31,   159,   183,   174,   175,   188,   170,
   171,   184,   191,   176,   192,   190,    62,    65,   185,     0,
   117,     0,     0,     0,   115,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,   118
};

static const short yycheck[] = {    19,
    78,    49,    55,    48,    89,    90,    91,     3,     4,     5,
     6,     7,    32,     9,    10,    11,     3,    13,     3,    15,
    16,    13,    18,    13,    20,    50,    22,    32,    20,    14,
    20,    51,    13,     3,     4,     5,     6,     7,    52,     9,
    10,    11,    23,    13,    50,    15,    16,    67,    18,   139,
    20,    12,    22,    49,    59,    51,    17,    51,    50,    55,
   138,     3,     4,     5,     6,    52,     3,     4,     5,     6,
    49,   141,    92,    93,    94,    51,   161,    53,    98,    49,
    51,    51,   172,   173,    55,    55,    51,   157,    31,   159,
    55,    27,    28,   183,   139,   140,    29,    30,   188,   172,
   173,    52,     0,    54,   174,     3,    51,    49,    50,    50,
   183,    52,    49,   158,   184,   188,    48,   170,    45,    46,
    47,   141,   142,   176,    60,    61,    49,   172,   173,    49,
   175,     0,    43,    44,     3,   155,   156,   157,   183,   159,
    50,    10,    52,   188,    35,    36,    37,    38,     3,    50,
    41,    52,    51,    52,   174,    24,    51,    52,    27,    83,
    84,    85,    86,    50,   184,    52,    69,    58,    71,    72,
    73,    74,    75,    76,    50,    50,    52,    52,    50,    50,
    52,    52,    87,    88,    81,    82,    49,    51,    49,    56,
     3,     9,    52,    51,    51,    57,    52,    49,    49,    49,
    49,    55,     8,     8,    51,     8,    51,    50,    50,    57,
    56,    51,     0,    57,     0,     0,    24,    27,   182,    -1,
    79,    -1,    -1,    -1,    77,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    80
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 9:
#line 85 "sematic.y"
{scope=max_scope; inc(&scope);;
    break;}
case 10:
#line 86 "sematic.y"
{scope=max_scope; inc(&scope);;
    break;}
case 13:
#line 94 "sematic.y"
{ mySymTab(yyvsp[-1].myst.typ,yyvsp[0].id,0,scope+1);;
    break;}
case 16:
#line 101 "sematic.y"
{ FILE *fp;fp=fopen("abc.txt","w+");fprintf(fp,"%s","main");;
    break;}
case 17:
#line 102 "sematic.y"
{ mySymTab(yyvsp[-1].myst.typ,yyvsp[0].id,0,scope);;
    break;}
case 18:
#line 105 "sematic.y"
{ mySymTab(yyvsp[-2].myst.typ,yyvsp[-1].id,0,scope);printf("kjsokfjsojof=====%s\n",yyvsp[-1].id);;
    break;}
case 19:
#line 106 "sematic.y"
{ mySymTab(yyvsp[-5].myst.typ,yyvsp[-4].id,yyvsp[-2].myst.n,scope);;
    break;}
case 20:
#line 109 "sematic.y"
{ yyval.myst.typ="Char";;
    break;}
case 21:
#line 110 "sematic.y"
{ yyval.myst.typ="Int";;
    break;}
case 49:
#line 154 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 50:
#line 157 "sematic.y"
{ yyval.myst = yyvsp[-2].myst = yyvsp[0].myst; ;
    break;}
case 51:
#line 158 "sematic.y"
{ yyvsp[-2].myst.n  = yyvsp[-2].myst.n + yyvsp[0].myst.n; yyval.myst.n = yyvsp[-2].myst.n; ;
    break;}
case 52:
#line 159 "sematic.y"
{ yyvsp[-2].myst.n = yyvsp[-2].myst.n - yyvsp[0].myst.n; yyval.myst.n = yyvsp[-2].myst.n ;
    break;}
case 53:
#line 160 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n * yyvsp[0].myst.n; yyval.myst.n = yyvsp[-2].myst.n ;
    break;}
case 54:
#line 161 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n / yyvsp[0].myst.n; yyval.myst.n = yyvsp[-2].myst.n ;
    break;}
case 56:
#line 163 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 58:
#line 167 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 60:
#line 171 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 62:
#line 175 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 64:
#line 179 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 67:
#line 184 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 72:
#line 191 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 73:
#line 194 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n + yyvsp[0].myst.n; printf("%d + %d = %d \n",yyvsp[-2].myst.n,yyvsp[0].myst.n,yyval.myst.n);;
    break;}
case 74:
#line 195 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n - yyvsp[0].myst.n; printf("%d - %d = %d \n",yyvsp[-2].myst.n,yyvsp[0].myst.n,yyval.myst.n);;
    break;}
case 75:
#line 196 "sematic.y"
{ yyval.myst = yyvsp[0].myst ;
    break;}
case 76:
#line 199 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n * yyvsp[0].myst.n; printf("%d * %d = %d \n",yyvsp[-2].myst.n,yyvsp[0].myst.n,yyval.myst.n);;
    break;}
case 77:
#line 200 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n / yyvsp[0].myst.n; printf("%d / %d = %d \n",yyvsp[-2].myst.n,yyvsp[0].myst.n,yyval.myst.n);;
    break;}
case 78:
#line 201 "sematic.y"
{ yyval.myst.n = yyvsp[-2].myst.n % yyvsp[0].myst.n; printf("%d % %d = %d \n",yyvsp[-2].myst.n,yyvsp[0].myst.n,yyval.myst.n);;
    break;}
case 79:
#line 202 "sematic.y"
{ yyval.myst = yyvsp[0].myst; ;
    break;}
case 80:
#line 205 "sematic.y"
{ yyval.myst.n=yyvsp[0].num;;
    break;}
case 81:
#line 206 "sematic.y"
{ yyval.myst.c=yyvsp[0].id;;
    break;}
case 82:
#line 207 "sematic.y"
{ yyval.myst.c=yyvsp[0].id;;
    break;}
case 83:
#line 208 "sematic.y"
{ context_check(yyvsp[-3].id,scope); yyval.myst.n=yyvsp[-1].num; yyval.myst.c=yyvsp[-3].id;;
    break;}
case 84:
#line 209 "sematic.y"
{ context_check(yyvsp[-2].id,scope);;
    break;}
case 85:
#line 210 "sematic.y"
{ context_check(yyvsp[0].id,scope);;
    break;}
case 86:
#line 211 "sematic.y"
{ yyval.myst.n=yyvsp[-1].num; yyval.myst.c=yyvsp[-1].id;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 213 "sematic.y"



extern char* yytext[];

extern void yyerror(char *s)
{
fprintf(stderr,"%s\n",s);
return;
}

void main(int argc, char **argv)
{

extern FILE *yyin;
yyin=fopen(argv[1],"r");
yyparse();
return;
}
